baseURL = "https://laslopaul.dev/"
locale = "en-us"
title = "laslopaul"
theme = [ "terminal" ]
enableRobotsTXT = true


[params]
description = "devops & homelab enthusiast"
author = "laslopaul"
keywords = [
"devops",
"homelab",
"kubernetes",
"linux",
"ansible",
"terraform"
]
defaultTheme = "dark"
disableThemeToggle = true
fullWidthTheme = true
centerTheme = false


[params.logo]
logoText = "laslopaul.dev"
logoHomeLink = "/"


[permalinks]
posts = "/:slug/"


[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1


[[menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 2


[markup.highlight]
noClasses = false


[caches.images]
dir = ":cacheDir/images"
